# File patterns to include in linting.
include = [ "docs/games/*.py" ]

# The number of spaces per indentation level.
indent-width = 4

# Following PEP8 guidelines and with the team's agreement,
# set the code line length to 99 characters.
line-length = 99

[format]
# Respect Brack, disallow tabs.
indent-style = "space"

# Prefer double quotes over single quotes.
quote-style = "double"

# Enforce trailing comma.
skip-magic-trailing-comma = false

[lint]
# Enable all linting rules.
select = [ "ALL" ]

# Ignore specific linting rules.
ignore = [
    "CPY001",
    "D100",   # Allow missing docstring in public module
    "D101",   # Allow missing docstring in public class
    "D102",   # Allow missing docstring in public method
    "D103",   # Allow missing docstring in public function
    "D104",   # Allow missing docstring in public package
    "D107",   # Allow missing docstring in `__init__`
    "D203",   # Ignore: incompatible with D211 (no-blank-line-before-class)
    "D213",   # Ignore: incompatible with D212 (multi-line-summary-first-line)
    "D401",   # Allow first line of docstring not to be in imperative mood
    "BLE001", # Allow catching blind exception
    "RUF001", # Allow full-width punctuation in strings (Japanese UI text)
    "RUF002", # Allow full-width punctuation in docstrings (Japanese)
    "RUF003", # Allow full-width punctuation in comments (Japanese)
    "COM812", # Conflicts with the formatter; the formatter manages trailing commas itself.
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = [ "ALL" ]

unfixable = [
    "T201", # Prevents auto-fixing print statements.
    "T203", # Prevents auto-fixing pprint statements.
]

[lint.pycodestyle]
max-doc-length = 79
